### ISSUE TITLE
New Resource: wiz_connector

### ISSUE THREAD

**Issue by gramsa49** [AxtonGrams/terraform-provider-wiz#11]
### Description

Add support for a new resource, wiz_connector, to manage Connectors within Wiz.

### Potential Terraform Configuration

```hcl
resource "wiz_connector" "test" {
  name        = "test"
  enabled     = true
  auth_params = jsonencode({})
  extra_config = jsonencode({
    "auditLogMonitorEnabled" : false,
    "excludedAccounts" : [],
    "excludedOUs" : []
  })
  type = jsonencode({
    "id" : "aws",
    "name" : "Amazon Web Services (AWS)",
    "categories" : [
      {
        "id" : "CloudPlatform",
        "name" : "Cloud platform"
      },
      {
        "id" : "UserDirectory",
        "name" : "User directory"
      },
      {
        "id" : "IAC",
        "name" : ""
      },
      {
        "id" : "CSPM",
        "name" : ""
      },
      {
        "id" : "SecurityInsight",
        "name" : ""
      }
    ],
    "technology" : {
      "id" : "2263",
      "name" : "AWS Account"
    },
    "authorizeUrls" : null
  })
}
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jschoombee** [comment]
I propose to split this out into separate resources, starting with aws. As the schemas differ for input and response, a single connector/deployment resource might get complex quite quickly
