### ISSUE TITLE
data-source for details for Wiz Subscription

### ISSUE THREAD

**Issue by DmitriSmirnovCTL** [AxtonGrams/terraform-provider-wiz#19]
### Description

Data source to lookup details for Wiz cloud subscription (similar to organization) will be useful

### Potential Terraform Configuration

```hcl
# Get the Wiz internal information for the Subscription based on the AWS Account ID

data "wiz_subscription" "account1" {
  search = "account1"
}
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by gramsa49** [comment]
Take a look at the stubbed documentation for this data source and let me know if it looks ok:
https://github.com/AxtonGrams/terraform-provider-wiz/blob/datasource_cloudaccounts/docs/data-sources/cloud_accounts.md

**Comment by DmitriSmirnovCTL** [comment]
Looks ok to me, thank you. Sample in docs would be nice to have, and corresponding link in 'wiz_project':

data "wiz_cloud_accounts" "aws-123456789" {
  filters {
        search="123456789"
  }
}

resource "wiz_project" "aws-project {
  name        = "aws-project"
  description = "aws-project"

cloud_account_link {
    cloud_account = tolist(data.wiz_cloud_accounts.aws-123456789.cloud_accounts)[0].id
    shared      = false
 }

  risk_profile {
    business_impact = "MBI"
  }
}

**Comment by gramsa49** [comment]
Thanks for the quick response.  I'll include an example before I merge the code.
