### ISSUE TITLE
Data source to retrieve the short id of the cloud configuration rule and host config rule 

### ISSUE THREAD

**Issue by i-am-srini** [AxtonGrams/terraform-provider-wiz#24]
### Description
Data source to retrieve the short id of the cloud configuration rule and host config rule 

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by gramsa49** [comment]
I would like to break this out into two new data sources:

- wiz_cloud_config_rules
- wiz_host_config_rules
