### ISSUE TITLE
Change default authentication endpoint to Cognito endpoint

### ISSUE THREAD

**Issue by gramsa49** [AxtonGrams/terraform-provider-wiz#44]
### Description

Change default authentication endpoint to Cognito endpoint  The default for [wiz_auth_url](https://registry.terraform.io/providers/AxtonGrams/wiz/latest/docs#wiz_auth_url) should be changed from https://auth.wiz.io/oauth/token to https://auth.app.wiz.io/oauth/token.

### References

https://docs.wiz.io/wiz-docs/docs/migrate-to-cognito#4-migrate-local-users-and-service-accounts

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by mario-fernandez-mm** [comment]
Verified, with that new wiz_auth_url the authentication works!
