### ISSUE TITLE
wiz_users datasource

### ISSUE THREAD

**Issue by jschoombee** [AxtonGrams/terraform-provider-wiz#48]
### Description

Please implement a wiz users datasource. In order to link idp or local wiz users to projects as owners, the internal wiz identifier needs to be passed.

### Potential Terraform Configuration

```hcl
data "wiz_users" "security_champions" {
  search = "alias@domain.com"
  authentication_source = "LEGACY" 
}
```

### References
relates to [open issue](https://github.com/AxtonGrams/terraform-provider-wiz/issues/29)

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by gramsa49** [comment]
I merged the PR for wiz_kubernetes_clusters.  Can you rebase the feature branch for wiz_users off main and push the changes?  This will resolve the merge conflicts here.

**Comment by jschoombee** [comment]
Thanks, also now has struct naming suggestion to match graphql schema as `UserConnection`
