### ISSUE TITLE
wiz_kubernetes_clusters datasource

### ISSUE THREAD

**Issue by jschoombee** [AxtonGrams/terraform-provider-wiz#51]
### Description

Please implement a wiz kubernetes cluster datasource. This is needed In order to link clusters to Wiz projects.

### Potential Terraform Configuration

```hcl
data "wiz_kubernetes_clusters" "myclusters" {
  external_ids = ["232412319201"]
  first        = 3
}
```

### References
relates to [open issue](https://github.com/AxtonGrams/terraform-provider-wiz/issues/29)

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by gramsa49** [comment]
Couple of proposed changes on naming of vendor struct and data source function to adhere to vendor naming and existing provider naming conventions.  If you agree and can sent a commit with the changes, this looks good to me to merge.

**Comment by jschoombee** [comment]
Thanks for the feedback on naming, changes applied upstream.
