### ISSUE TITLE
Support for Kubernetes Connector (Helm)

### ISSUE THREAD

**Issue by ruzickap** [AxtonGrams/terraform-provider-wiz#65]
### Description

Would it be possible to add the "Kubernetes Connector (Helm)"?

This is needed to connect k8s clusters using Helm to Wiz.

![image](https://user-images.githubusercontent.com/1434387/218501710-1c527135-1139-4c3a-b18c-f1835e32b20e.png)

Details: https://docs.wiz.io/wiz-docs/docs/auto-connect-clusters-helm

**Comment by jschoombee** [comment]
We need the same. Will have something ready hopefully early next week.

**Comment by ruzickap** [comment]
Thank you...

You may also consider adding "Kubernetes Admission Controller" too :-)

<img width="382" alt="image" src="https://user-images.githubusercontent.com/1434387/224335990-4459ef6a-18bc-40ed-af70-416629379656.png">

You may need it as well...

**Comment by jschoombee** [comment]
> Thank you...
> 
> You may also consider adding "Kubernetes Admission Controller" too :-)
> 
> <img alt="image" width="382" src="https://user-images.githubusercontent.com/1434387/224335990-4459ef6a-18bc-40ed-af70-416629379656.png">
> 
> You may need it as well...

Indeed, will implement the following, `BROKER` type will be for helm:
```
// ServiceAccountType enum
var ServiceAccountType = []string{
	"THIRD_PARTY",
	"SENSOR",
	"KUBERNETES_ADMISSION_CONTROLLER",
	"BROKER",
}
